roads = {
    'Shambu': { 'utility': 4, 'neighbors': [('Gedo', False)], 'terminal': True },
    'Fincha': { 'utility': 5, 'neighbors': [('Gedo', False)], 'terminal': True },
    'Gimbi': { 'utility': 8, 'neighbors': [('Nekemte', False)], 'terminal': True },
    'Gedo': { 'utility': 0, 'neighbors': [('Shambu', False), ('Fincha', False)], 'terminal': False },
    'Nekemte': { 'utility': 0, 'neighbors': [('Gimbi', False), ('Limu', False)], 'terminal': False },
    'Hossana': { 'utility': 6, 'neighbors': [('Worabe', False)], 'terminal': True },
    'Durame': { 'utility': 5, 'neighbors': [('Worabe', False)], 'terminal': True },
    'Bench Naji': { 'utility': 5, 'neighbors': [('Wolkite', False)], 'terminal': True },
    'Tepi': { 'utility': 6, 'neighbors': [('Wolkite', False)], 'terminal': True },
    'Wolkite': { 'utility': 0, 'neighbors': [('Tepi', False), ('Bench Naji', False)], 'terminal': False },
    'Buta Jirra': { 'utility': 0, 'neighbors': [('Addis Ababa', False), ('Wolkite', False), ('Worabe', False)], 'terminal': False },
    'Adama': { 'utility': 0, 'neighbors': [('Addis Ababa', True), ('Diredawa', False), ('Mojo', False)], 'terminal': False },
    'Diredawa': { 'utility': 0, 'neighbors': [('Chiro', False), ('Harar', False)], 'terminal': False },
    'Harar': { 'utility': 10, 'neighbors': [('Diredawa', False)], 'terminal': True },
    'Chiro': { 'utility': 6, 'neighbors': [('Diredawa', False)], 'terminal': True },
    'Dilla': { 'utility': 9, 'neighbors': [('Mojo', False)], 'terminal': True },
    'Kaffa': { 'utility': 7, 'neighbors': [('Mojo', False)], 'terminal': True },
    'Addis Ababa': { 'utility': 0, 'neighbors': [('Adama', False), ('Ambo', False), ('Buta Jirra', False)], 'terminal': False },
    'Mojo': { 'utility': 0, 'neighbors': [('Adama', True), ('Dilla', False), ('Kaffa', False)], 'terminal': False },
    'Worabe': { 'utility': 0, 'neighbors': [('Hossana', False), ('Durame', False), ('Buta Jirra', False)], 'terminal': False },
    'Limu': { 'utility': 0, 'neighbors': [('Nekemte', False)], 'terminal': True },
    'Ambo': { 'utility': 0, 'neighbors': [('Addis Ababa', False), ('Nekemte', False), ('Gedo', False)], 'terminal': True }
}